version: '3'

services:
  python:
    build:
      dockerfile: .docker/Dockerfile
      context: .
    volumes:
      - ./src:/src
    command: bash -c "pip3 install -r requirements.txt && /bin/bash"
    tty: true
